### ISSUE TITLE
Java version?

### ISSUE THREAD

**Issue by goodale** [josephwoodward/CKFinderJcrop#2]
I'm interested in your plugin but am using the Java version of CKFinder (e.g. servlets on the server side instead of PHP).  

any plans to add Java service?  I'd be able to hiring out that work if there's interest.

Cheers,
Steve

**Comment by josephwoodward** [comment]
Hi Goodale,

I wasn't planning to. There's not too much programming involved so I can't imagine it would be very difficult to port to Java? It's mainly the image uploading and resizing that needs to be done.

**Comment by goodale** [comment]
Thanks JoeMighty.  I completely agree.  was just looking to save some time and see if anything was in the works or if there was an opportunity to hire it out.
